substitutions:
  name: ag-office
  friendly_name: AG-Office
  name_add_mac_suffix: "false"

# WiFi credentials
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

# Dashboard import for ESPHome web interface
dashboard_import:
  package_import_url: github://a3rosol/airgradient_esphome/airgradient-pro.yaml
  import_full_config: false

packages:
  # Packages from fork (github://a3rosol/airgradient_esphome)
  board: github://a3rosol/airgradient_esphome/packages/esp32_d1_mini32_board.yaml
  ld2410: github://a3rosol/airgradient_esphome/packages/sensor_ld2410.yaml
  pm_2.5: github://a3rosol/airgradient_esphome/packages/sensor_pms5003.yaml
  co2: github://a3rosol/airgradient_esphome/packages/sensor_s8.yaml
  temp_humidity: github://a3rosol/airgradient_esphome/packages/sensor_sht40.yaml
  tvoc: github://a3rosol/airgradient_esphome/packages/sensor_sgp41.yaml
  display: github://a3rosol/airgradient_esphome/packages/display_sh1106_single_page.yaml
  config_button: github://a3rosol/airgradient_esphome/packages/config_button.yaml
  wifi: github://a3rosol/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://a3rosol/airgradient_esphome/packages/sensor_uptime.yaml

  # Commented out (not needed):
  # captive_portal: github://a3rosol/airgradient_esphome/packages/captive_portal.yaml
  # airgradient_api: github://a3rosol/airgradient_esphome/packages/airgradient_api_d1_mini.yaml

# Override config button pin (GPIO23 = D7)
binary_sensor:
  - id: !extend config_button
    pin:
      number: 23
      mode: INPUT_PULLUP
      inverted: true
