substitutions:
  # LD2410 detection parameters - adjust based on your room
  ld2410_timeout: "150s"
  ld2410_max_move_distance: "6m"
  ld2410_max_still_distance: "0.75m"

ld2410:
  uart_id: ld2410_uart
  timeout: ${ld2410_timeout}
  max_move_distance: ${ld2410_max_move_distance}
  max_still_distance: ${ld2410_max_still_distance}
  # Gate sensitivity thresholds (g0-g8, lower = more sensitive)
  # These values are from the inspiration config - adjust as needed
  g0_move_threshold: 10
  g0_still_threshold: 20
  g1_move_threshold: 10
  g1_still_threshold: 20
  g2_move_threshold: 20
  g2_still_threshold: 21
  g3_move_threshold: 30
  g3_still_threshold: 31
  g4_move_threshold: 40
  g4_still_threshold: 41
  g5_move_threshold: 50
  g5_still_threshold: 51
  g6_move_threshold: 60
  g6_still_threshold: 61
  g7_move_threshold: 70
  g7_still_threshold: 71
  g8_move_threshold: 80
  g8_still_threshold: 81

binary_sensor:
  # Direct GPIO presence output from LD2410C
  - platform: gpio
    name: "Occupancy"
    id: occupancy_sensor
    pin: 35  # input-only pin on ESP32
    device_class: occupancy

  # LD2410 component presence detection (via UART)
  - platform: ld2410
    has_target:
      name: "Presence"
      id: ld2410_presence
    has_moving_target:
      name: "Moving Target"
      id: ld2410_moving_target
    has_still_target:
      name: "Still Target"
      id: ld2410_still_target

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving Distance"
      id: ld2410_moving_distance
    still_distance:
      name: "Still Distance"
      id: ld2410_still_distance
    moving_energy:
      name: "Moving Energy"
      id: ld2410_moving_energy
    still_energy:
      name: "Still Energy"
      id: ld2410_still_energy
    detection_distance:
      name: "Detection Distance"
      id: ld2410_detection_distance
